### ISSUE TITLE
Project not available in Cocoapods

### ISSUE THREAD

**Issue by csotiriou** [checkmobi/checkmobi_ios_swift#3]
It seems that the actual pod file is not committed to the official Cocoapods repository.

I had to write `pod 'CheckMobiSwift', :git=> 'https://github.com/checkmobi/checkmobi_ios_swift', :branch=> 'master` to my pod file in order to get it to load.

**Comment by kiranruth** [comment]
+1

**Comment by muratyasarr** [comment]
@csotiriou Thanks for pointing this out. It helped me install the pods. But just a quick note for anyone who copies from your snippet,  `pod 'CheckMobiSwift', :git=> 'https://github.com/checkmobi/checkmobi_ios_swift', :branch=> 'master'` We just shouldn't forget to add a single quote to the end of _'master_.

Cheers,
Murat

**Comment by mohammad19991** [comment]
+1

**Comment by checkmobi** [comment]
Please see Remote Config SDK . This is the new way to integrate CheckMobi in swift and objective c projects : https://github.com/checkmobi/remote-config-sdk-ios
