### ISSUE TITLE
Swift 3.0 support?

### ISSUE THREAD

**Issue by muratyasarr** [checkmobi/checkmobi_ios_swift#4]
When will checkmobi_ios_swift library support Swift 3.0 ?

**Comment by checkmobi** [comment]
Hello,
There is no plan right now. I suggest you to use the objective c sdk because it's possible to use objective c code in swift from what I see. http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

Also if you want you can fix the code and send a pull request.

**Comment by checkmobi** [comment]
Please see Remote Config SDK . This is the new way to integrate CheckMobi in swift and objective c projects : https://github.com/checkmobi/remote-config-sdk-ios
